org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.5
max_minecraft_version=1.22
yarn_mappings=1.21.5+build.1
loader_version=0.16.14

maven_group=me.justahuman
mod_id=claimmaps
archives_base_name=ClaimMaps
mod_version=1.0.0

mod_name=ClaimMaps
mod_description=A mod adding support for claim plugins such as HuskTowns and GriefPrevention to common map mods like JourneyMap, Xaeros Mini & World Map, etc.

fabric_version=0.128.1+1.21.5
worldmap_version=1.39.10_Fabric_1.21.5
minimap_version=25.2.7_Fabric_1.21.5
journeymap_version=1.21.5-6.0.0-beta.52+fabric
journeymap_api_version=2.0.0-1.21.5-SNAPSHOT