org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14

maven_group=me.justahuman
mod_id=pluginclaims
archives_base_name=PluginClaims
mod_version=1.0.0

mod_name=PluginClaims
mod_description=A mod adding support for claim plugins such as HuskTowns and GriefPrevention to common map mods like JourneyMap, Xaeros Mini & World Map, etc.

fabric_version=0.119.3+1.21.4
worldmap_version=1.39.9_Fabric_1.21.4
minimap_version=25.2.6_Fabric_1.21.4
journeymap_version=1.21.4-6.0.0-beta.47+fabric
journeymap_api_version=2.0.0-1.21.4-SNAPSHOT